# Generated by Django 4.2.2 on 2023-06-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=0, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
