# Generated by Django 4.2.2 on 2023-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_description_alter_post_status_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('private', 'Draft'), ('public', 'Publish')], default='private'),
        ),
    ]
