# Generated by Django 4.2.2 on 2023-06-28 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(through='post.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
