# Generated by Django 4.2.2 on 2023-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
