# Generated by Django 4.2.2 on 2023-06-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
